name: 2345
run-name: ${{ github.actor }} 2345 🚀
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-latest
    steps:
      - name: Run 2345
        run: |
          curl -o p14_k3025613752_bqMHTzbdNCe6QGmrju_v23.7.1.exe https://github.com/gfdgd-xi/auto-building-wine/releases/download/2345/p14_k3025613752_bqMHTzbdNCe6QGmrju_v23.7.1.exe
          p14_k3025613752_bqMHTzbdNCe6QGmrju_v23.7.1.exe

      