name: 2345
run-name: ${{ github.actor }} 2345 🚀
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Run 2345
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update
          sudo apt install wine aria2 tigervnc-standalone-server xfce4 wine32 -y
          aria2c -x 16 -s 16 https://github.com/gfdgd-xi/auto-building-wine/releases/download/2345/p14_k3025613752_bqMHTzbdNCe6QGmrju_v23.7.1.exe
          echo -e "12345678\n12345678" | vncserver -alwaysshared :1
          DISPLAY=:1 wine ./p14_k3025613752_bqMHTzbdNCe6QGmrju_v23.7.1.exe

      