name: Building BOX86
run-name: ${{ github.actor }} Building BOX86 🚀
on:
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Building Wine
        env: 
          GUSER: ${{ secrets.GUSER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          UPLOADURL: ${{ secrets.UPLOADURL }}
        run: |
          # 配置编译容器
          sudo apt update
          sudo apt install aria2 debootstrap neofetch python3 curl -y
          neofetch
          # 编译 amd64 wine
          git clone https://github.com/gfdgd-xi/auto-building-wine --depth=1
          cd auto-building-wine
          bash build-box86.sh
      - name: upload result(box86-armhf)
        uses: actions/upload-artifact@v1
        with:
          name: box86-armhf
          path: /tmp/result/box86_armhf.deb
      